# -*- coding: utf-8 -*-
"""labreport5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uorwjBBKXsjNtXmrpjS3M9pceVyZ6Q6U
"""

import streamlit as st
import torch
import torch.nn.functional as F
from torchvision import models
from PIL import Image
import pandas as pd

# Step 1: Streamlit page configuration
st.set_page_config(
    page_title="Image Classification using ResNet18",
    layout="centered"
)

st.title("🖼️ Computer Vision Image Classification")
st.write(
    "This web application classifies an uploaded image using a "
    "pre-trained ResNet18 model running on CPU."
)


# Step 2–3: Load pretrained ResNet18 (CPU only)
device = torch.device("cpu")

@st.cache_resource
def load_resnet_model():
    weights = models.ResNet18_Weights.DEFAULT
    model = models.resnet18(weights=weights)
    model.eval()
    model.to(device)
    return model, weights

model, weights = load_resnet_model()

# Step 5: Image preprocessing (ImageNet standard)
transform = weights.transforms()
class_labels = weights.meta["categories"]

# Step 6: Image uploader
uploaded_image = st.file_uploader(
    "Upload an image (JPG / PNG)",
    type=["jpg", "jpeg", "png"]
)

if uploaded_image is not None:

    # Display uploaded image
    image = Image.open(uploaded_image).convert("RGB")
    st.image(image, caption="Uploaded Image", use_column_width=True)


    # Step 7: Convert image to tensor and inference
    input_tensor = transform(image).unsqueeze(0).to(device)

    with torch.no_grad():
        output = model(input_tensor)


    # Step 8: Softmax and Top-5 predictions
    probabilities = F.softmax(output, dim=1)[0]
    top5_probs, top5_indices = torch.topk(probabilities, 5)

    results = []
    for i in range(5):
        results.append({
            "Predicted Class": class_labels[top5_indices[i]],
            "Probability (%)": round(top5_probs[i].item() * 100, 2)
        })

    results_df = pd.DataFrame(results)

    st.subheader("🔍 Top-5 Prediction Results")
    st.table(results_df)

    # Step 9: Bar chart visualization
    st.subheader("📊 Prediction Probability Chart")
    st.bar_chart(results_df.set_index("Predicted Class"))


# Step 10: Model explanation (for discussion section)
st.markdown("---")
st.subheader("🧠 Classification Process Explanation")
st.write(
    """
    1. The uploaded image is resized and normalized using ImageNet standards.
    2. ResNet18 extracts hierarchical visual features using convolutional layers.
    3. The final layer outputs class scores for 1000 ImageNet categories.
    4. Softmax converts these scores into probability values.
    5. The top-5 classes with the highest probabilities are displayed.

    Since ResNet18 is a single-label classifier, it predicts the most visually
    dominant object in the image.
    """
)